### ISSUE TITLE
Not working at all on Android.

### ISSUE THREAD

**Issue by St-Yihang** [sanyuered/WeChat-MiniProgram-AR-TFJS#1]
I am using Andoird 10.
When running the program on my mobile, it will remian  on the  "warming up..."  status. When I removed the "warmning up" part, it will not detect any thing, I can only see :"onCamerFrame" logged out.

**Comment by sanyuered** [comment]
The program replaces "face-api.js" with "face-landmarks-detection". Please try the new program.
