### ISSUE TITLE
Super cool! Will it work for other Tensorflow models?

### ISSUE THREAD

**Issue by louiselessel** [sanyuered/WeChat-MiniProgram-AR-TFJS#2]
Hi!

@sanyuered great work on this, I can't wait to test it out! 
Have you tried other models, like the bodypix tensorflow that extracts backgrounds?

Where did you find the ressources for loading in the blazeface model  (or bodypix for that matter) - that step confuses me a little and I can see that you are self hosting? Can you explain this part?

**Comment by sanyuered** [comment]
The blazeface model is downloaded from TensorFlow Hub. Because some areas can not access the TensorFlow hub, so self hosting.  
The TensorFlow models have been included in the folder "/assets/blazeface_v1" and  "/assets/facemesh_v1".
