### ISSUE TITLE
模拟器上运行正常，真机报错

### ISSUE THREAD

**Issue by wulixu** [sanyuered/WeChat-MiniProgram-AR-TFJS#4]
![image](https://user-images.githubusercontent.com/3402267/143671900-ace1514b-0686-4ef1-a54f-7df5d050c7a1.png)

**Comment by sanyuered** [comment]
1、我用iPhone和Android2台手机测试，运行正常。推测是真机上的小程序配置问题。

真机上的小程序打开调试模式或者设置request合法域名为模型下载地址的域名。

人脸检测
var BLAZEFACE_MODEL_URL = 'https://m.sanyue.red/demo/tfjs/blazeface_v1';

人脸特征点检测
var FACEMESH_GRAPHMODEL_PATH = 'https://m.sanyue.red/demo/tfjs/facemesh_v1';

2、如果使用微信开发者工具重新“构建npm“，上面的模型下载地址会变为tfhub的地址。如果无法访问tfhub，需要改为你的手机可以访问的地址。
